//1. DEPARTMENT 테이블의 구조를 확인하라.
DESC DEPARTMENTS;

//2. DEPARTMENT 테이블의 모든 내용을 출력하라.
SELECT *
FROM DEPARTMENTS;

//3. EMPLOYEE의 LAST NAME, JOB CODE, HIRE DATE, EMPLOYEE NUMBER를 출력하라. 사원번호가 가장 앞에 나와야 한다.
SELECT  employee_id, last_name, job_id, hire_date, HIRE_DATE AS STARTDATE
FROM EMPLOYEES;

//4.
SELECT DISTINCT job_ID
FROM EMPLOYEES;

//5.
SELECT JOB_ID
FROM JOBS;

//6.
SELECT FIRST_NAME ||' '|| LAST_NAME AS "EMPLOYEE", SALARY
FROM EMPLOYEES;

SELECT DEPARTMENT_NAME, DEPARTMENT_ID
FROM DEPARTMENTS;

SELECT *
FROM COUNTRIES;